name: Setup Python

description: 'Setup environment'
runs:
  using: 'composite'

  env:
    # Configure a constant location for the uv cache
    UV_CACHE_DIR: /tmp/.uv-cache

  steps:
    - name: Set up uv
      run: curl -LsSf https://astral.sh/uv/0.3.3/install.sh | sh
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install dependencies
      run: uv sync --no-install-project
      shell: bash
