name: Setup Python

runs:
  using: 'composite'
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install
      shell: bash
