name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: /.github/actions/setup

      - name: Run linter
        run: |
          source .venv/bin/activate
          ruff format .
          ruff check .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: /.github/actions/setup

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
