name: CI

on: [push, pull_request]

jobs:
  lint:
    env:
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run linter and type checker
        run: |
          uv run ruff format .
          uv run ruff check .
          uv run mypy .

      - name: Minimize uv cache
        run: uv cache prune --ci

  tests:
    env:
      # Configure a constant location for the uv cache
      UV_CACHE_DIR: /tmp/.uv-cache

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: |
          uv run coverage run --source=app -m pytest
          uv run coverage report --show-missing
          uv run coverage html

      - name: Minimize uv cache
        run: uv cache prune --ci
