name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Run linter
        run: |
          source .venv/bin/activate
          ruff format .
          ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
